packages:
  - "packages/*"

allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false
  '@fortawesome/free-solid-svg-icons': false
  "@parcel/watcher": true
  "core-js": false
  esbuild: true
  "unrs-resolver": true
