/**
 * Full @merchi/product-form-sdk runtime for window.MerchiProductFormSdk.
 * Keep in sync with merchi_api/common/js/product_form_gate.cjs SDK_EXPORTS.
 */
import {
  SDK_VERSION,
  serializeJob,
  nonEmptyGroups,
  formatCurrency,
  urlFor,
  createPricing,
  createProductFormRuntime,
  productHasGroups,
  groupFieldsOf,
  independentFieldsOf,
  isOptionQuantityGridProduct,
  buildProductFormJob,
  jobToFormState,
  selectionsToVariations,
  Section,
  Stack,
  Card,
  Heading,
  Text,
  Divider,
  Field,
  GroupRows,
  OptionQuantityGrid,
  ProductFormProvider,
  ProductFormShell,
  ProductFormActions,
  useProductForm,
  OPTION_FIELD_TYPES,
  theme,
} from '@merchi/product-form-sdk';

export const MerchiProductFormSdkExternals = {
  SDK_VERSION,
  serializeJob,
  nonEmptyGroups,
  formatCurrency,
  urlFor,
  createPricing,
  createProductFormRuntime,
  productHasGroups,
  groupFieldsOf,
  independentFieldsOf,
  isOptionQuantityGridProduct,
  buildProductFormJob,
  jobToFormState,
  selectionsToVariations,
  Section,
  Stack,
  Card,
  Heading,
  Text,
  Divider,
  Field,
  GroupRows,
  OptionQuantityGrid,
  ProductFormProvider,
  ProductFormShell,
  ProductFormActions,
  useProductForm,
  OPTION_FIELD_TYPES,
  theme,
};
